version: '3.8'

services:
  # 1. Serviço da sua API Java (plantcare-api)
  app:
    build: .
    container_name: java-api
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8080:8080"
    environment:
      # Configs para sua API se conectar ao container 'oracle-db'
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=280103
      - SERVER_SERVLET_CONTEXT_PATH=/api
    depends_on:
      oracle-db:
        condition: service_healthy

  # 2. Serviço do Banco de Dados Oracle
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      # Define a senha dos usuários SYSTEM/SYS para '280103'
      - ORACLE_PWD=280103
      - ORACLE_PDB_LSNR_PORT=1521
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10m
    volumes:
      # Garante que os dados do banco não se percam
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data: