CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;

CREATE TABLE T_PC_USUARIOS (
    ID_USUARIO BIGINT PRIMARY KEY DEFAULT NEXTVAL('SEQ_USUARIO'),
    NM_USUARIO VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL
);