CREATE TABLE T_PC_USUARIOS (
                               ID_USUARIO NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               NM_USUARIO VARCHAR2(200) NOT NULL,
                               EMAIL VARCHAR2(255) NOT NULL,
                               SENHA VARCHAR2(255) NOT NULL,
                               ROLE VARCHAR2(20) NOT NULL
);