CREATE SEQUENCE SEQ_PLANTA START WITH 1 INCREMENT BY 1;

CREATE TABLE T_PC_PLANTAS (
    ID_PLANTA BIGINT PRIMARY KEY DEFAULT NEXTVAL('SEQ_PLANTA'),
    NM_PLANTA VARCHAR(255) NOT NULL,
    TIPO_PLANTA VARCHAR(255) NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP,
    IMAGEM VARCHAR(500),
    VL_UMIDADE DOUBLE PRECISION,
    VL_TEMPERATURA DOUBLE PRECISION,
    STATUS VARCHAR(100),
    ID_USUARIO BIGINT NOT NULL,

    CONSTRAINT FK_PLANTA_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES T_PC_USUARIOS(ID_USUARIO)
);