CREATE TABLE T_PC_PLANTAS (
                              ID_PLANTA NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              NM_PLANTA VARCHAR2(255) NOT NULL,
                              TIPO_PLANTA VARCHAR2(255) NOT NULL,
                              DT_CADASTRO TIMESTAMP NOT NULL,
                              DT_ATUALIZACAO TIMESTAMP,
                              IMAGEM VARCHAR2(500),
                              VL_UMIDADE FLOAT,
                              VL_TEMPERATURA FLOAT,
                              STATUS VARCHAR2(100),
                              ID_USUARIO NUMBER(19) NOT NULL,

                              CONSTRAINT FK_PLANTA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES T_PC_USUARIOS(ID_USUARIO)
);