CREATE TABLE T_PC_SENSOR (
                             ID_SENSOR NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             TP_SENSOR VARCHAR2(50) NOT NULL,
                             ID_PLANTA NUMBER(19),

                             CONSTRAINT FK_SENSOR_PLANTA
                                 FOREIGN KEY (ID_PLANTA)
                                     REFERENCES T_PC_PLANTAS(ID_PLANTA)
);