CREATE SEQUENCE SEQ_SENSOR START WITH 1 INCREMENT BY 1;

CREATE TABLE T_PC_SENSOR (
    ID_SENSOR BIGINT PRIMARY KEY DEFAULT NEXTVAL('SEQ_SENSOR'),
    TP_SENSOR VARCHAR(50) NOT NULL,
    ID_PLANTA BIGINT,

    CONSTRAINT FK_SENSOR_PLANTA
        FOREIGN KEY (ID_PLANTA)
        REFERENCES T_PC_PLANTAS(ID_PLANTA)
);