CREATE TABLE T_PC_LEITURA (
                              ID_LEITURA NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              DT_LEITURA TIMESTAMP NOT NULL,
                              VALOR FLOAT NOT NULL,
                              ID_SENSOR NUMBER(19),

                              CONSTRAINT FK_LEITURA_SENSOR
                                  FOREIGN KEY (ID_SENSOR)
                                      REFERENCES T_PC_SENSOR(ID_SENSOR)
);