CREATE SEQUENCE SEQ_LEITURA START WITH 1 INCREMENT BY 1;

CREATE TABLE T_PC_LEITURA (
    ID_LEITURA BIGINT PRIMARY KEY DEFAULT NEXTVAL('SEQ_LEITURA'),
    DT_LEITURA TIMESTAMP NOT NULL,
    VALOR DOUBLE PRECISION NOT NULL,
    ID_SENSOR BIGINT,

    CONSTRAINT FK_LEITURA_SENSOR
        FOREIGN KEY (ID_SENSOR)
        REFERENCES T_PC_SENSOR(ID_SENSOR)
);