CREATE SEQUENCE SEQ_ALERTA START WITH 1 INCREMENT BY 1;

CREATE TABLE T_PC_ALERTAS (
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('SEQ_ALERTA'),
    DT_REGISTRO_ALERTA TIMESTAMP NOT NULL,
    MSG_ALERTA VARCHAR(500) NOT NULL,
    ID_PLANTA BIGINT,

    CONSTRAINT FK_ALERTA_PLANTA
        FOREIGN KEY (ID_PLANTA)
        REFERENCES T_PC_PLANTAS(ID_PLANTA)
);