CREATE TABLE T_PC_ALERTAS (
                              ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              DT_REGISTRO_ALERTA TIMESTAMP NOT NULL,
                              MSG_ALERTA VARCHAR2(500) NOT NULL,
                              ID_PLANTA NUMBER(19),

                              CONSTRAINT FK_ALERTA_PLANTA
                                  FOREIGN KEY (ID_PLANTA)
                                      REFERENCES T_PC_PLANTAS(ID_PLANTA)
);