CREATE TABLE T_PC_RECOMENDACAO (
                                   ID_RECOMENDACAO NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   DT_REGISTRO_RECOMENDACAO TIMESTAMP NOT NULL,
                                   MSG_RECOMENDACAO VARCHAR2(500) NOT NULL,
                                   ID_PLANTA NUMBER(19),

                                   CONSTRAINT FK_RECOMENDACAO_PLANTA
                                       FOREIGN KEY (ID_PLANTA)
                                           REFERENCES T_PC_PLANTAS(ID_PLANTA)
);