CREATE SEQUENCE SEQ_RECOMENDACAO START WITH 1 INCREMENT BY 1;

CREATE TABLE T_PC_RECOMENDACAO (
    ID_RECOMENDACAO BIGINT PRIMARY KEY DEFAULT NEXTVAL('SEQ_RECOMENDACAO'),
    DT_REGISTRO_RECOMENDACAO TIMESTAMP NOT NULL,
    MSG_RECOMENDACAO VARCHAR(500) NOT NULL,
    ID_PLANTA BIGINT,

    CONSTRAINT FK_RECOMENDACAO_PLANTA
        FOREIGN KEY (ID_PLANTA)
        REFERENCES T_PC_PLANTAS(ID_PLANTA)
);